# Getting Started with PyTorch
Pytorch is a replacement for numpy. Its just faster and uses the power of GPUs
* What is a Tensor?
    * A tensor is similar to ndarray, but can be used on a GPU to make the computations faster

In [1]:
# Construct a 5x3 tensor uninitialized

from __future__ import print_function
import torch

In [3]:
torch.empty(5,3)

tensor([[ 0.0000,  2.0000,  0.0000],
        [ 2.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [9]:
# Randomly initialized Tensor 
torch.rand(5,3)

tensor([[ 0.6766,  0.0261,  0.3516],
        [ 0.3813,  0.8592,  0.7167],
        [ 0.0283,  0.2327,  0.9152],
        [ 0.8097,  0.6036,  0.6212],
        [ 0.0103,  0.9726,  0.4808]])

In [11]:
# Matrix filled with zeroes
torch.zeros(5,4, dtype=torch.int)

tensor([[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]], dtype=torch.int32)

In [30]:
# Construct a tensor directly from data. Make it 3 dimensional
x = torch.tensor([[[0,9,7,9],[6,7,8,6]],[[0,9,7,9],[6,7,8,6]]], dtype=torch.double)
print(x)

tensor([[[ 0.,  9.,  7.,  9.],
         [ 6.,  7.,  8.,  6.]],

        [[ 0.,  9.,  7.,  9.],
         [ 6.,  7.,  8.,  6.]]], dtype=torch.float64)


In [20]:
# Construct tensor with only ones with like shape 
torch.ones_like(x)

tensor([[[ 1,  1,  1,  1],
         [ 1,  1,  1,  1]],

        [[ 1,  1,  1,  1],
         [ 1,  1,  1,  1]]])

In [22]:
#  Construct tensor with random numbers with a like shape 
torch.rand_like(x, dtype= torch.double)

tensor([[[ 0.3768,  0.2960,  0.5817,  0.7760],
         [ 0.6758,  0.5623,  0.3428,  0.8346]],

        [[ 0.6423,  0.8714,  0.3498,  0.6603],
         [ 0.7114,  0.1292,  0.7114,  0.8972]]], dtype=torch.float64)

In [23]:
x.size()

torch.Size([2, 2, 4])

In [31]:
y = torch.rand_like(x, dtype= torch.double)

In [32]:
x + y

tensor([[[ 0.5196,  9.5421,  7.2905,  9.9490],
         [ 6.6698,  7.5436,  8.4130,  6.3636]],

        [[ 0.9486,  9.9364,  7.7246,  9.6139],
         [ 6.3074,  7.6495,  8.3376,  6.8223]]], dtype=torch.float64)

In [35]:
result = torch.empty_like(x, dtype= torch.double)
torch.add(x,y, out= result)
result

tensor([[[ 0.5196,  9.5421,  7.2905,  9.9490],
         [ 6.6698,  7.5436,  8.4130,  6.3636]],

        [[ 0.9486,  9.9364,  7.7246,  9.6139],
         [ 6.3074,  7.6495,  8.3376,  6.8223]]], dtype=torch.float64)

In [40]:
x.add_(x)

tensor([[[   0.,  288.,  224.,  288.],
         [ 192.,  224.,  256.,  192.]],

        [[   0.,  288.,  224.,  288.],
         [ 192.,  224.,  256.,  192.]]], dtype=torch.float64)

In [49]:
x[:,:1,-2:]

tensor([[[ 224.,  288.]],

        [[ 224.,  288.]]], dtype=torch.float64)

In [50]:
# if you want to reshape your tensor

In [56]:
x.shape
z= torch.rand(16)

In [63]:
x.view(2,2,2,2)

tensor([[[[   0.,  288.],
          [ 224.,  288.]],

         [[ 192.,  224.],
          [ 256.,  192.]]],


        [[[   0.,  288.],
          [ 224.,  288.]],

         [[ 192.,  224.],
          [ 256.,  192.]]]], dtype=torch.float64)

In [67]:
torch.rand(1).item()

0.8973182439804077

In [68]:
torch.cuda.is_available()

False